@ -1,65 +0,0 @@
packaging_format = 2

id = "h5ai"
name = "h5ai"
description.en = "Modern HTTP web server index for NGINX"
description.fr = "Serveur moderne d'index pour NGINX"

version = "0.30.0~ynh11"

maintainers = ["alexAubin"]

[upstream]
license = "MIT"
website = "https://larsjung.de/h5ai/"
demo = "https://larsjung.de/h5ai/demo/"
admindoc = "https://larsjung.de/h5ai/"
code = "https://github.com/lrsjng/h5ai"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/documents"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/lrsjng/h5ai/archive/refs/tags/v0.30.0.tar.gz"
        sha256 = "f1638557ec79e6fe6bd9303b1e9d8d0180a620dbf4811b6c194befa24769800c"

    [resources.system_user]
    allow_sftp = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm, php8.2-gd, ffmpeg, imagemagick"

    [resources.nodejs]
    version = "10.15"