#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=500M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tmpdir=$(mktemp -d)

ynh_setup_source --dest_dir="$tmpdir"
pushd $tmpdir
    ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app npm run build
    mv build/_h5ai $install_dir/_h5ai
popd

ynh_safe_rm $tmpdir

chmod 700 "$install_dir/_h5ai/private/conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
