#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=500M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tmpdir=$(mktemp -d)

ynh_setup_source --dest_dir="$tmpdir"

pushd $tmpdir
    cp $install_dir/_h5ai/private/conf/options.json ./options.json.bkp
    ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app npm run build
    ynh_safe_rm $install_dir/_h5ai
    mv build/_h5ai $install_dir/_h5ai
    cp ./options.json.bkp $install_dir/_h5ai/private/conf/options.json
popd

ynh_safe_rm $tmpdir

chown -R $app:www-data "$install_dir/_h5ai"
chmod 700 "$install_dir/_h5ai/private/conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
